guerrero/estado/urls.py
from django.urls import path, include
from estado.views import demonio_print
from estado.views import Estadoview,Estadoinsertar,Estadoeditar,Estadoeliminar,Partecuerpoview,Partecuerpoinsertar,Partecuerpoeditar,Partecuerpoeliminar,Detallecuerpoview,Detallecuerpoinsertar,Detallecuerpoeditar,Detallecuerpoeliminar,Demonioview,Demonioinsertar,Demonioeditar,Demonioeliminar,Batallaview,Batallainsertar,Batallaeditar,Batallaeliminar


urlpatterns = [
    path('Estado', Estadoview.as_view(), name='Estados'),
    path('Estado/new', Estadoinsertar.as_view(), name='AgregarE'),
    path('Estado/edit/<int:pk>', Estadoeditar.as_view(), name='EditarE'),
    path('Estado/delete/<int:pk>', Estadoeliminar.as_view(), name='EliminarE'),

    path('Partecuerpo', Partecuerpoview.as_view(), name='Partecuerpos'),
    path('Partecuerpo/new', Partecuerpoinsertar.as_view(), name='AgregarP'),
    path('Partecuerpo/edit/<int:pk>', Partecuerpoeditar.as_view(), name='EditarP'),
    path('Partecuerpo/delete/<int:pk>', Partecuerpoeliminar.as_view(), name='EliminarP'),

    path('Detallecuerpo', Detallecuerpoview.as_view(), name='Detallecuerpos'),
    path('Detallecuerpo/new', Detallecuerpoinsertar.as_view(), name='AgregarDC'),
    path('Detallecuerpo/edit/<int:pk>', Detallecuerpoeditar.as_view(), name='EditarDC'),
    path('Detallecuerpo/delete/<int:pk>', Detallecuerpoeliminar.as_view(), name='EliminarDC'),

    path('', Batallaview.as_view(), name='Batallas'),
    path('Batalla/new', Batallainsertar.as_view(), name='AgregarB'),
    path('Batalla/edit/<int:pk>', Batallaeditar.as_view(), name='EditarB'),
    path('Batalla/delete/<int:pk>', Batallaeliminar.as_view(), name='EliminarB'),

    path('Demonio', Demonioview.as_view(), name='Demonios'),
    path('Demonio/new', Demonioinsertar.as_view(), name='AgregarD'),
    path('Demonio/edit/<int:pk>', Demonioeditar.as_view(), name='EditarD'),
    path('Demonio/delete/<int:pk>', Demonioeliminar.as_view(), name='EliminarD'),
    path('Demonio/print',demonio_print,name='demonio_print'),
    path('Demonio/print/<int:pk>',demonio_print,name='demonio_print_one'),
  ]

guerrero/guerrero/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Estado',include(('estado.urls','Estado'),namespace='Estado')),
    path('',include(('estado.urls','Batalla'),namespace='Batalla')),
    path('Partecuerpo',include(('estado.urls','Partecuerpos'),namespace='Partecuerpo')),
    path('Detallecuerpo',include(('estado.urls','Detallecuerpo'),namespace='Detallecuerpo')),
    path('Demonio',include(('estado.urls','Demonio'),namespace='Demonio')),
]

guerrero/home/urls.py
from django.contrib import admin
from django.urls import include, path
from home.views import Home
from django.contrib.auth import views as auth_views

urlpatterns= [
    path('',Home.as_view(),name='home'),
]

guerrero/templates/container/container.html
<!doctype html>

<html lang="es">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">

  <meta name="author" content="">


  <title>
Batallas
  </title>
<script src="https://kit.fontawesome.com/e6d44f8b60.js" crossorigin="anonymous"></script>
  <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/navbars/">

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <!-- Bootstrap core CSS -->
  <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="navbar.css" rel="stylesheet">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>

  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>
    <script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
    <link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css">
    <script src="//cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" charset="utf-8"></script>

</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
<a class="navbar-brand" href="#">Hyakkimaru</a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
 <span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="navbarNav">
 <ul class="navbar-nav">
   <li class="nav-item active">
     <a class="nav-link" href="{% url 'Batalla:Batallas' %}">Home <span class="sr-only">(current)</span></a>
   </li>
   <li class="nav-item">
     <a class="nav-link" href="{% url 'Estado:Estados' %}">Estados</a>
   </li>
   <li class="nav-item">
     <a class="nav-link" href="{% url 'Detallecuerpo:Detallecuerpos' %}">Detalles Partecuerpo</a>
   </li>
   <li class="nav-item">
     <a class="nav-link" href="{% url 'Batalla:Batallas' %}">Batallas</a>
   </li>
   <li class="nav-item">
     <a class="nav-link" href="{% url 'Demonio:Demonios' %}">Demonios</a>
   </li>
   <li class="nav-item">
     <a class="nav-link" href="{% url 'Partecuerpo:Partecuerpos' %}">Parte del cuerpo</a>
   </li>

 </ul>
</div>
</nav>
<br>
<div class="container">
<div class="card">
  <div class="card-body">
  {% block contenido %}Se puede cambiar{% endblock contenido %}
</div>
</div>
</div>
  <script type="text/javascript">
  $(document).ready( function () {
  $('#myTable').DataTable();
} );
  </script>

  <!-- Bootstrap core JavaScript
    ================================================== -->
  <!-- Placed at the end of the document so the pages load faster -->
</body>

</html>