guerrero/estado/urls.py
from django.urls import path, include
from estado.views import demonio_print
from estado.views import Estadoview,Estadoinsertar,Estadoeditar,Estadoeliminar,Partecuerpoview,Partecuerpoinsertar,Partecuerpoeditar,Partecuerpoeliminar,Detallecuerpoview,Detallecuerpoinsertar,Detallecuerpoeditar,Detallecuerpoeliminar,Demonioview,Demonioinsertar,Demonioeditar,Demonioeliminar,Batallaview,Batallainsertar,Batallaeditar,Batallaeliminar


urlpatterns = [
    path('Estado', Estadoview.as_view(), name='Estados'),
    path('Estado/new', Estadoinsertar.as_view(), name='AgregarE'),
    path('Estado/edit/<int:pk>', Estadoeditar.as_view(), name='EditarE'),
    path('Estado/delete/<int:pk>', Estadoeliminar.as_view(), name='EliminarE'),

    path('Partecuerpo', Partecuerpoview.as_view(), name='Partecuerpos'),
    path('Partecuerpo/new', Partecuerpoinsertar.as_view(), name='AgregarP'),
    path('Partecuerpo/edit/<int:pk>', Partecuerpoeditar.as_view(), name='EditarP'),
    path('Partecuerpo/delete/<int:pk>', Partecuerpoeliminar.as_view(), name='EliminarP'),

    path('Detallecuerpo', Detallecuerpoview.as_view(), name='Detallecuerpos'),
    path('Detallecuerpo/new', Detallecuerpoinsertar.as_view(), name='AgregarDC'),
    path('Detallecuerpo/edit/<int:pk>', Detallecuerpoeditar.as_view(), name='EditarDC'),
    path('Detallecuerpo/delete/<int:pk>', Detallecuerpoeliminar.as_view(), name='EliminarDC'),

    path('', Batallaview.as_view(), name='Batallas'),
    path('Batalla/new', Batallainsertar.as_view(), name='AgregarB'),
    path('Batalla/edit/<int:pk>', Batallaeditar.as_view(), name='EditarB'),
    path('Batalla/delete/<int:pk>', Batallaeliminar.as_view(), name='EliminarB'),

    path('Demonio', Demonioview.as_view(), name='Demonios'),
    path('Demonio/new', Demonioinsertar.as_view(), name='AgregarD'),
    path('Demonio/edit/<int:pk>', Demonioeditar.as_view(), name='EditarD'),
    path('Demonio/delete/<int:pk>', Demonioeliminar.as_view(), name='EliminarD'),
    path('Demonio/print',demonio_print,name='demonio_print'),
    path('Demonio/print/<int:pk>',demonio_print,name='demonio_print_one'),
  ]

guerrero/guerrero/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Estado',include(('estado.urls','Estado'),namespace='Estado')),
    path('',include(('estado.urls','Batalla'),namespace='Batalla')),
    path('Partecuerpo',include(('estado.urls','Partecuerpos'),namespace='Partecuerpo')),
    path('Detallecuerpo',include(('estado.urls','Detallecuerpo'),namespace='Detallecuerpo')),
    path('Demonio',include(('estado.urls','Demonio'),namespace='Demonio')),
]

guerrero/home/urls.py
from django.contrib import admin
from django.urls import include, path
from home.views import Home
from django.contrib.auth import views as auth_views

urlpatterns= [
    path('',Home.as_view(),name='home'),
]

guerrero/estado/models.py
from django.db import models


# modelo de estado

class Estado(models.Model):
    EstadoNombre = models.CharField(
       max_length = 50,
       )
    def __str__(self):
        return '{}'.format(self.EstadoNombre)
    def save(self):
        self.EstadoNombre = self.EstadoNombre.upper()
        super(Estado,self).save()
class Meta:
    verbose_name_plural='Articulos'


#modelo del parte de cuerpo

class Partecuerpo(models.Model):
    CuerpoNombre = models.CharField(
        max_length = 50,
    )
    def __str__(self):
        return '{}'.format(self.CuerpoNombre)
    def save(self):
        self.CuerpoNombre= self.CuerpoNombre.upper()
        super(Partecuerpo,self).save()
class Meta:
    verbose_name_plural='Partes del ceurpo'


#modelo de los detalles del cuerpo

class Detallecuerpo(models.Model):
    partecuerpo=models.ForeignKey(Partecuerpo, on_delete=models.CASCADE)
    estado=models.ForeignKey(Estado, on_delete=models.CASCADE)
    def __str__(self):
        return 'EL DEMONIO {} ESTA PARTE DEL CUERPO : {}  '.format(self.estado.EstadoNombre ,self.partecuerpo.CuerpoNombre )
    def save(self):
        super(Detallecuerpo,self).save()
class Meta:
    verbose_name_plural='Detalles del cuerpo'


#modelo del Demonio

class Demonio(models.Model):
    DemonioNombre = models.CharField(
        max_length = 50,
    )
    detallecuerpo=models.ForeignKey(Detallecuerpo, on_delete=models.CASCADE)
    def __str__(self):
        return '{}'.format(self.DemonioNombre)
    def save(self):
        self.DemonioNombre= self.DemonioNombre.upper()
        super(Demonio,self).save()
class Meta:
    verbose_name_plural='Demonios'


#modelo de batalla

class Batalla(models.Model):
    demonio=models.ForeignKey(Demonio, on_delete=models.CASCADE)
    estado=models.ForeignKey(Estado, on_delete=models.CASCADE)
    def __str__(self):
        return '{}:{}'.format(self.demonio.DemonioNombre, self.estado.EstadoNombre)
    def save(self):
        super(Batalla,self).save()
class Meta:
    verbose_name_plural='batallas'

guerrero/estado/forms.py
from django import forms
from estado.models import Estado,Partecuerpo,Detallecuerpo,Demonio,Batalla


# formulario de estado

class Estadoform(forms.ModelForm):
    class Meta:
        model = Estado
        fields = ['EstadoNombre']
        labels = {'Estado ' : 'ingrese el  nombre'}
        widget={'EstadoNombre' : forms.TextInput()}

    def __init__(self,*args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'})


#formulario de partecuerpo

class Partecuerpoform(forms.ModelForm):
    class Meta:
        model = Partecuerpo
        fields = ['CuerpoNombre']
        labels = {'parte del cuerpo ' : 'ingrese el  nombre'}
        widget={'CuerpoNombre' : forms.TextInput()}
    def __init__(self,*args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'})


#formulario  los detalles del cuerpo

class Detallecuerpoform(forms.ModelForm):
    class Meta:
        model = Detallecuerpo
        fields = ['partecuerpo','estado']
        labels = {'parte del cuerpo' : 'escoja el  nombre',
                   'estado':'escoja el  nombre' }
        widget={'partecuerpo' : forms.TextInput(),
                'estado' : forms.TextInput()
               }
    def __init__(self,*args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'})


#formulario  los Demonios

class Demonioform(forms.ModelForm):
    class Meta:
        model = Demonio
        fields = ['DemonioNombre','detallecuerpo']
        labels = {'Nombre del demonio' : 'ingrese el  nombre',
                  'detallecuerpo':'escoja la parte del cuerpo' }
        widget={'DemonioNombre' : forms.TextInput(),
                'detallecuerpo' : forms.TextInput()
               }
    def __init__(self,*args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'})


#formulario  los Demonios

class Batallaform(forms.ModelForm):
    class Meta:
        model = Batalla
        fields = ['demonio','estado']
        labels = {'Nombre del demonio' : 'escoja el demonio',
                  'estado':'escoja el estado' }
        widget={'demonio' : forms.TextInput(),
                'estado' : forms.TextInput()
               }
    def __init__(self,*args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'})

guerrero/estado/views.py
from django.shortcuts import render
from estado.models import Estado,Partecuerpo,Detallecuerpo,Demonio,Batalla
from django.urls import  reverse_lazy
from estado.forms import Estadoform,Partecuerpoform,Detallecuerpoform,Demonioform,Batallaform
from django.views import generic
from django.http import  HttpResponse
# Create your views here.

#Vistas de Estados
class Estadoview(generic.ListView):
    model = Estado
    template_name = 'listar_estado.html'
    context_object_name = 'estado'
class Estadoinsertar(generic.CreateView):
     model = Estado
     context_object_name = 'estado'
     template_name = 'form_estado.html'
     form_class = Estadoform
     success_url=reverse_lazy("Estado:Estados")
class Estadoeditar(generic.UpdateView):
     model = Estado
     context_object_name = 'estado'
     template_name = 'form_estado.html'
     form_class = Estadoform
     success_url=reverse_lazy("Estado:Estados")
class Estadoeliminar(generic.DeleteView):
     model = Estado
     context_object_name = 'estado'
     template_name = 'delete_estado.html'
     form_class = Estadoform
     success_url=reverse_lazy("Estado:Estados")
#Vistas de Partecuerpo
class Partecuerpoview(generic.ListView):
    model = Partecuerpo
    template_name = 'listar_partecuerpo.html'
    context_object_name = 'partecuerpo'
class Partecuerpoinsertar(generic.CreateView):
     model = Partecuerpo
     context_object_name = 'partecuerpo'
     template_name = 'form_partecuerpo.html'
     form_class = Partecuerpoform
     success_url=reverse_lazy("Partecuerpo:Partecuerpos")
class Partecuerpoeditar(generic.UpdateView):
     model = Partecuerpo
     context_object_name = 'partecuerpo'
     template_name = 'form_partecuerpo.html'
     form_class = Partecuerpoform
     success_url=reverse_lazy("Partecuerpo:Partecuerpos")
class Partecuerpoeliminar(generic.DeleteView):
     model = Partecuerpo
     context_object_name = 'partecuerpo'
     template_name = 'delete_partecuerpo.html'
     form_class = Partecuerpoform
     success_url=reverse_lazy("Partecuerpo:Partecuerpos")
#Vistas de Detallecuerpo
class Detallecuerpoview(generic.ListView):
    model = Detallecuerpo
    template_name = 'listar_detallecuerpo.html'
    context_object_name = 'detallecuerpo'
class Detallecuerpoinsertar(generic.CreateView):
     model = Detallecuerpo
     context_object_name = 'detallecuerpo'
     template_name = 'form_detallecuerpo.html'
     form_class = Detallecuerpoform
     success_url=reverse_lazy("Detallecuerpo:Detallecuerpos")
class Detallecuerpoeditar(generic.UpdateView):
     model = Detallecuerpo
     context_object_name = 'detallecuerpo'
     template_name = 'form_detallecuerpo.html'
     form_class = Detallecuerpoform
     success_url=reverse_lazy("Detallecuerpo:Detallecuerpos")
class Detallecuerpoeliminar(generic.DeleteView):
     model = Detallecuerpo
     context_object_name = 'detallecuerpo'
     template_name = 'delete_detallecuerpo.html'
     form_class = Detallecuerpoform
     success_url=reverse_lazy("Detallecuerpo:Detallecuerpos")
#Vistas de Demonio
class Demonioview(generic.ListView):
    model = Demonio
    template_name = 'listar_demonio.html'
    context_object_name = 'demonio'
class Demonioinsertar(generic.CreateView):
     model = Demonio
     context_object_name = 'demonio'
     template_name = 'form_demonio.html'
     form_class = Demonioform
     success_url=reverse_lazy("Demonio:Demonios")
class Demonioeditar(generic.UpdateView):
     model = Demonio
     context_object_name = 'demonio'
     template_name = 'form_demonio.html'
     form_class = Demonioform
     success_url=reverse_lazy("Demonio:Demonios")
class Demonioeliminar(generic.DeleteView):
     model = Demonio
     context_object_name = 'demonio'
     template_name = 'delete_demonio.html'
     form_class = Demonioform
     success_url=reverse_lazy("Demonio:Demonios")
#Vistas de Batalla
class Batallaview(generic.ListView):
    model = Batalla
    template_name = 'listar_batalla.html'
    context_object_name = 'batalla'
class Batallainsertar(generic.CreateView):
     model = Batalla
     context_object_name = 'batalla'
     template_name = 'form_batalla.html'
     form_class = Batallaform
     success_url=reverse_lazy("Batalla:Batallas")
class Batallaeditar(generic.UpdateView):
     model = Batalla
     context_object_name = 'batalla'
     template_name = 'form_batalla.html'
     form_class = Batallaform
     success_url=reverse_lazy("Batalla:Batallas")
class Batallaeliminar(generic.DeleteView):
     model = Batalla
     context_object_name = 'batalla'
     template_name = 'delete_batalla.html'
     form_class = Batallaform
     success_url=reverse_lazy("Batalla:Batallas")


def demonio_print(self, pk=None):
    import io
    from reportlab.platypus import SimpleDocTemplate, Paragraph, TableStyle
    from reportlab.lib.styles import getSampleStyleSheet
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import letter
    from reportlab.platypus import Table

    response = HttpResponse(content_type='application/pdf')
    buff = io.BytesIO()
    doc = SimpleDocTemplate(buff,
                            pagesize=letter,
                            rightMargin=40,
                            leftMargin=40,
                            topMargin=60,
                            bottomMargin=18,
                            )
    demonios = []
    styles = getSampleStyleSheet()
    header = Paragraph("Listado de Demonio", styles['Heading1'])
    demonios.append(header)
    headings = ('Id', 'demonio', 'detalle ')
    if not pk:
        todosdemonio = [(p.id, p.DemonioNombre, p.detallecuerpo)
                           for p in Demonio.objects.all().order_by('pk')]
    else:
        todosdemonio = [(p.id, p.DemonioNombre, p.detallecuerpo)
                           for p in Demonio.objects.filter(id=pk)]

    t = Table([headings] + todosdemonio)
    t.setStyle(TableStyle(
        [
            ('GRID', (0, 0), (3, -1), 1, colors.dodgerblue),
            ('LINEBELOW', (0, 0), (-1, 0), 2, colors.darkblue),
            ('BACKGROUND', (0, 0), (-1, 0), colors.dodgerblue)
        ]
    ))

    demonios.append(t)
    doc.build(demonios)
    response.write(buff.getvalue())
    buff.close()
    return response

guerrero/estado/templates/delete_batalla.html
{% extends 'container/container.html' %}
{% block contenido %}
<form method="post">
  <div class="panel panel-default">
    <div class="panel-heading">
      Eliminar
    </div>
    <div class="panel-body">
      {% csrf_token %}
      <div class="alert alert-succes">
        Eliminar
      <button type="submit" class="btn btn-danger">
        <span class="fa fa-delete">Eliminar</span>
      </button
        <a href="{% url 'Batalla:Batallas' %}" class="btn btn-succes">
          <span class="fa fa-undo"></span>
        </a>
    </div>
  </div>
</form>
{% endblock contenido %}

guerrero/estado/templates/delete_demonio.html
{% extends 'container/container.html' %}
{% block contenido %}
<form method="post">
  <div class="panel panel-default">
    <div class="panel-heading">
      Eliminar
    </div>
    <div class="panel-body">
      {% csrf_token %}
      <div class="alert alert-succes">
        Eliminar
      <button type="submit" class="btn btn-danger">
        <span class="fa fa-delete">Eliminar</span>
      </button
        <a href="{% url 'Demonio:Demonios' %}" class="btn btn-succes">
          <span class="fa fa-undo"></span>
        </a>
    </div>
  </div>
</form>
{% endblock contenido %}

guerrero/estado/templates/delete_detallecuerpo.html
{% extends 'container/container.html' %}
{% block contenido %}
<form method="post">
  <div class="panel panel-default">
    <div class="panel-heading">
      Eliminar
    </div>
    <div class="panel-body">
      {% csrf_token %}
      <div class="alert alert-succes">
        Eliminar
      <button type="submit" class="btn btn-danger">
        <span class="fa fa-delete">Eliminar</span>
      </button
        <a href="{% url 'Detallecuerpo:Detallecuerpos' %}" class="btn btn-succes">
          <span class="fa fa-undo"></span>
        </a>
    </div>
  </div>
</form>
{% endblock contenido %}

guerrero/estado/templates/delete_estado.html
{% extends 'container/container.html' %}
{% block contenido %}
<form method="post">
  <div class="panel panel-default">
    <div class="panel-heading">
      Eliminar
    </div>
    <div class="panel-body">
      {% csrf_token %}
      <div class="alert alert-succes">
        Eliminar
      <button type="submit" class="btn btn-danger">
        <span class="fa fa-delete">Eliminar</span>
      </button
        <a href="{% url 'Estado:Estados' %}" class="btn btn-succes">
          <span class="fa fa-undo"></span>
        </a>
    </div>
  </div>
</form>
{% endblock contenido %}

guerrero/estado/templates/delete_partecuerpo.html
{% extends 'container/container.html' %}
{% block contenido %}
<form method="post">
  <div class="panel panel-default">
    <div class="panel-heading">
      Eliminar
    </div>
    <div class="panel-body">
      {% csrf_token %}
      <div class="alert alert-succes">
        Eliminar
      <button type="submit" class="btn btn-danger">
        <span class="fa fa-delete">Eliminar</span>
      </button
        <a href="{% url 'Partecuerpo:Partecuerpo' %}" class="btn btn-succes">
          <span class="fa fa-undo"></span>
        </a>
    </div>
  </div>
</form>
{% endblock contenido %}

guerrero/estado/templates/form_batalla.html
{% extends 'container/container.html' %}
{% block contenido %}
<form method="post">
  <div class="panel panel-default">
    <div class="panel-heading">
    </div>
      <div class="panel-body">
         {% csrf_token %}
         {{form.as_p}}
        <button type="submit" class="btn btn-danger">
          <span class="fa fa-save">Guardar</span>
          </button>
      </div>
  </div>
</form>
{% endblock contenido %}

guerrero/estado/templates/form_demonio.html
{% extends 'container/container.html' %}
{% block contenido %}
<form method="post">
  <div class="panel panel-default">
    <div class="panel-heading">
    </div>
      <div class="panel-body">
         {% csrf_token %}
         {{form.as_p}}
        <button type="submit" class="btn btn-danger">
          <span class="fa fa-save">Guardar</span>
          </button>
      </div>
  </div>
</form>
{% endblock contenido %}

guerrero/estado/templates/form_detallecuerpo.html
{% extends 'container/container.html' %}
{% block contenido %}
<form method="post">
  <div class="panel panel-default">
    <div class="panel-heading">
    </div>
      <div class="panel-body">
         {% csrf_token %}
         {{form.as_p}}
        <button type="submit" class="btn btn-danger">
          <span class="fa fa-save">Guardar</span>
          </button>
      </div>
  </div>
</form>
{% endblock contenido %}

guerrero/estado/templates/form_estado.html
{% extends 'container/container.html' %}
{% block contenido %}
<form method="post">
  <div class="panel panel-default">
    <div class="panel-heading">
     
    </div>
      <div class="panel-body">
         {% csrf_token %}
         {{form.as_p}}
        <button type="submit" class="btn btn-danger">
          <span class="fa fa-save">Guardar</span>
          </button>
      </div>
  </div>
</form>
{% endblock contenido %}

guerrero/estado/templates/form_partecuerpo.html
{% extends 'container/container.html' %}
{% block contenido %}
<form method="post">
  <div class="panel panel-default">
    <div class="panel-heading">
    </div>
      <div class="panel-body">
         {% csrf_token %}
         {{form.as_p}}
        <button type="submit" class="btn btn-danger">
          <span class="fa fa-save">Guardar</span>
          </button>
      </div>
  </div>
</form>
{% endblock contenido %}

guerrero/estado/templates/listar_demonio.html
{% extends 'container/container.html' %}
{% block contenido %}
<div class="panel panel-primary">
    <div class="panel-heading">
      <h1>
        Demonios<span class="badge badge-danger"><i class="fab fa-optin-monster fa-2x"></i>  </span>
      </h1>
    </div>
</div>
<div class="panel-body"></div>
<table class="table table-striped table-bordered table-hover border ">
    <thead>
        <tr>
            <th>Id </th>
            <th>Demonio</th>
            <th>Estado de Partes</th>
            <th>Acciones</th>
        </tr>
    </thead>
    {% csrf_token %}
    <tbody>
        {% for item in demonio  %}
        <tr >
            <td>
                {{item.id}}
            </td>
            <td>
                {{item.DemonioNombre}}
            </td>
            <td>
                {{item.detallecuerpo}}
            </td>


             <td>
               <div class=" btn-group  dropright">
                  <button class="btn btn-danger dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Acciones
                  </button>
                  <div class="dropdown-menu p-3" aria-labelledby="dropdownMenuButton">
                      <a  class="btn btn-outline-danger btn-block " href="{% url 'Demonio:EliminarD' item.id  %}">eliminar</a>
                      <a class="btn btn-outline-info  btn-block mt-2" href="{% url 'Demonio:EditarD' item.id  %}">Editar</a>
                  </div>
                </div>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
 <a class="btn btn-outline-primary" href="{% url 'Demonio:AgregarD' %}">Agregar</a>
  <a class="btn btn-outline-danger" href="{% url 'Demonio:demonio_print' %}">Imprimir</a>
{%endblock contenido%}

guerrero/estado/templates/listar_detallecuerpo.html
{% extends 'container/container.html' %}
{% block contenido %}
<div class="panel panel-primary">
    <div class="panel-heading">
        <h1>
          Estados de Extremidades<span class="badge badge-success"><i class="fas fa-male fa-2x"></i></span>
        </h1>
    </div>
</div>
<div class="panel-body"></div>
<table class="table table-striped table-bordered table-hover">
    <thead>
        <tr>
            <th>Id </th>
            <th>parte cuerpo</th>
            <th>Estado</th>
            <th>Acciones</th>

        </tr>
    </thead>
    {% csrf_token %}
    <tbody>
        {% for item in detallecuerpo  %}
        <tr>
            <td>
                {{item.id}}
            </td>
            <td>
                {{item.partecuerpo}}
            </td>
            <td>
              {{item.estado}}
            </td>


             <td>
               <div class=" btn-group dropright">
                  <button class="btn btn-success dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Acciones
                  </button>
                  <div class="dropdown-menu p-3" aria-labelledby="dropdownMenuButton">
                      <a  class="btn btn-outline-danger btn-block " href="{% url 'Detallecuerpo:EliminarDC' item.id  %}">eliminar</a>
                      <a class="btn btn-outline-info  btn-block mt-2" href="{% url 'Detallecuerpo:EditarDC' item.id  %}">Editar</a>
                  </div>
                </div>


            </td>

        </tr>
        {% endfor %}
    </tbody>
</table>
 <a class="btn btn-outline-primary" href="{% url 'Detallecuerpo:AgregarDC' %}">Agregar</a>
{%endblock contenido%}

guerrero/estado/templates/listar_estado.html
{% extends 'container/container.html' %}
{% block contenido %}
<div class="panel panel-primary">
    <div class="panel-heading">
      <h1>
        Estados Generales<span class="badge badge-primary"><i class="fas fa-arrows-alt-h fa-2x"></i></span>
      </h1>
    </div>
</div>
<div class="panel-body" ></div>
<table class="table table-striped table-hover" id="myTable">
    <thead>
        <tr>
            <th>Id </th>
            <th>Estado</th>
            <th>Acciones</th>
        </tr>
    </thead>
    {% csrf_token %}
    <tbody>
        {% for item in estado  %}
        <tr>
            <td>
                {{item.id}}
            </td>
            <td>
                {{item.EstadoNombre}}
            </td>

             <td>
               <div class=" btn-group dropright">
                  <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Acciones
                  </button>
                  <div class="dropdown-menu p-3" aria-labelledby="dropdownMenuButton">
                      <a  class="btn btn-outline-danger btn-block " href="{% url 'Estado:EliminarE' item.id  %}">eliminar</a>
                      <a class="btn btn-outline-info  btn-block mt-2" href="{% url 'Estado:EditarE' item.id  %}">Editar</a>
                  </div>
                </div>

                <a
            </td>

        </tr>
        {% endfor %}
    </tbody>
</table>
 <a class="btn btn-outline-primary" href="{% url 'Estado:AgregarE' %}">Agregar Estado</a>

{%endblock contenido%}

guerrero/estado/templates/listar_partecuerpo.html
{% extends 'container/container.html' %}
{% block contenido %}
<div class="panel panel-primary">
    <div class="panel-heading">
        <h1>
          Partes del cuerpo<span class="badge badge-success"><i class="fas fa-baby fa-2x"></i></span>
        </h1>
    </div>
</div>
<div class="panel-body"></div>
<table class="table table-striped table-bordered table-hover">
    <thead>
        <tr>
            <th>Id </th>
            <th>Parte</th>
            <th>acciones</th>


        </tr>
    </thead>
    {% csrf_token %}
    <tbody>
        {% for item in partecuerpo  %}
        <tr>
            <td>
                {{item.id}}
            </td>
            <td>
                {{item.CuerpoNombre}}
            </td>

             <td>
               <div class=" btn-group dropright">
                  <button class="btn btn-success dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Acciones
                  </button>
                  <div class="dropdown-menu p-3" aria-labelledby="dropdownMenuButton">
                      <a  class="btn btn-outline-danger btn-block " href="{% url 'Partecuerpo:EliminarP' item.id  %}">eliminar</a>
                      <a class="btn btn-outline-info  btn-block mt-2"href="{% url 'Partecuerpo:EditarP' item.id  %}">Editar</a>
                  </div>
                </div>
            </td>

        </tr>
        {% endfor %}
    </tbody>
</table>
 <a class="btn btn-outline-primary" href="{% url 'Partecuerpo:AgregarP' %}">Agregar</a>
{%endblock contenido%}